### PR TITLE
Save to dev dependences

### PR DESCRIPTION
**Pull request by RobertJGabriel**
Hey,

Thought it would be useful to add it as a dev-dependences over normally. Cause isn't this more for development  testing :) Sorry if incorrect. Love the repo

Also added some markdown tweaks for highlighting.

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Thanks for this 👍

**Comment by wmacjn** [comment]
# lightcrawler

**Comment by Artith1987** [comment]
thank for this

**Comment by Artith1987** [comment]
Report file external media

**Pull request merged**
